FROM denoland/deno:2.5.2

WORKDIR /app

COPY ./server/src/ ./server/src/

COPY deno.json deno.lock drizzle.config.ts /app/

RUN chown -R deno:deno /app

USER deno

RUN deno cache --node-modules-dir=auto server/src/server.ts

EXPOSE 3001

CMD ["run", "--allow-net", "--allow-read", "--allow-env", "server/src/server.ts"]