FROM denoland/deno:2.5.2 AS build

WORKDIR /app

COPY deno.json deno.lock package.json ./

COPY . .

RUN deno task build

FROM caddy:2-alpine

WORKDIR /usr/share/caddy

COPY Caddyfile /etc/caddy/Caddyfile

COPY --from=build /app/web/dist .
